---
title: DH@NYU
timezone: UTC
email: dh.help@nyu.edu
long_title: "Welcome to Digital Humanities at <br>New York University."
description: "Here you'll find sit amet, consectetur adipiscing elit. Sed eu elit in diam congue vehicula non sed magna. Aenean sit amet odio auctor, bibendum est eget, ultricies justo. Phasellus aliquam diam nec purus tincidunt lacinia. Duis eu porta enim, a fermentum eros. Phasellus placerat rutrum molestie."

baseurl: ''
url: 'https://nyu-dh.github.io'
future: true
source: src

permalink: pretty
logo-image-url: images/logo.png
github_username: 'nyu-dh'
twitter_username: 'nyu_dh'
markdown: kramdown

menu:
  - label: People
    link: '/people/'
  - label: Projects
    link: '/projects/'
  - label: Funding
    link: '/funding/'
  - label: Certificate Program
    link: '/certificate/'
  - label: Consultations & Resources
    link: '/consultations-and-resources/'
  - label: Get Involved
    link: '/get-involved/'

collections:
  updates:
    title: Updates
    output: true
    # permalink: "/:collection/:name"
  events:
    title: Events
    output: true
    # permalink: "/:collection/:name"
    layout: events
  projects:
    title: Projects
    output: true
    # permalink: "/:collection/:name"
    layout: project

search:
  index: index.json
